extends: relaxed

ignore: |
  vendor/
  dev-tools/vendor/

rules:
  indentation:
    spaces: 2
  line-length: disable
  quoted-strings:
    quote-type: single
    required: only-when-needed
  trailing-spaces: enable
