name: "Setup Cache"

inputs:
  os:
    description: 'OS version'
    required: true
  php:
    description: 'PHP version'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get Composer cache directory
      id: composer-cache-dir
      shell: bash
      run: echo "dir=$(composer config cache-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache-dir.outputs.dir }}
        key: composer-${{ inputs.os }}-${{ inputs.php }}-${{ hashFiles('**/composer.*') }}
        restore-keys: |
          composer-${{ inputs.os }}-${{ inputs.php }}-
          composer-${{ inputs.os }}-
          composer-
