name: "Install composer deps"

inputs:
  composer-flags:
    description: 'Composer flags'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 5
        retry_wait_seconds: 30
        command: composer update --optimize-autoloader --no-interaction --no-progress --no-scripts ${{ matrix.composer-flags }} # --no-scripts to avoid installing dev-tools for all jobs on CI level

    - name: Report versions
      shell: bash
      run: composer info -D
