<?php

declare(strict_types=1);

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace PhpCsFixer\Fixer\Operator;

use PhpCsFixer\AbstractFixer;
use PhpCsFixer\Fixer\ConfigurableFixerInterface;
use PhpCsFixer\Fixer\ConfigurableFixerTrait;
use PhpCsFixer\FixerConfiguration\FixerConfigurationResolver;
use PhpCsFixer\FixerConfiguration\FixerConfigurationResolverInterface;
use PhpCsFixer\FixerConfiguration\FixerOptionBuilder;
use PhpCsFixer\FixerDefinition\CodeSample;
use PhpCsFixer\FixerDefinition\FixerDefinition;
use PhpCsFixer\FixerDefinition\FixerDefinitionInterface;
use PhpCsFixer\Tokenizer\Token;
use PhpCsFixer\Tokenizer\Tokens;

/**
 * @phpstan-type _AutogeneratedInputConfiguration array{
 *  use_parentheses?: bool,
 * }
 * @phpstan-type _AutogeneratedComputedConfiguration array{
 *  use_parentheses: bool,
 * }
 *
 * @implements ConfigurableFixerInterface<_AutogeneratedInputConfiguration, _AutogeneratedComputedConfiguration>
 *
 * @author Jérôme Gamez <jerome@gamez.name>
 *
 * @no-named-arguments Parameter names are not covered by the backward compatibility promise.
 */
final class NegatedInstanceofWithParenthesesFixer extends AbstractFixer implements ConfigurableFixerInterface
{
    /** @use ConfigurableFixerTrait<_AutogeneratedInputConfiguration, _AutogeneratedComputedConfiguration> */
    use ConfigurableFixerTrait;

    public function getDefinition(): FixerDefinitionInterface
    {
        return new FixerDefinition(
            'Negated `instanceof` expressions must (not) be wrapped in parentheses.',
            [
                new CodeSample(
                    "<?php\n!\$foo instanceof Foo;\n",
                ),
                new CodeSample(
                    "<?php\n!(\$foo instanceof Foo);\n",
                    ['use_parentheses' => false],
                ),
            ],
        );
    }

    public function isCandidate(Tokens $tokens): bool
    {
        return $tokens->isTokenKindFound(\T_INSTANCEOF);
    }

    public function createConfigurationDefinition(): FixerConfigurationResolverInterface
    {
        return new FixerConfigurationResolver([
            (new FixerOptionBuilder('use_parentheses', 'Whether negated `instanceof` expressions should be wrapped in parentheses or not.'))
                ->setAllowedTypes(['bool'])
                ->setDefault(true)
                ->getOption(),
        ]);
    }

    protected function applyFix(\SplFileInfo $file, Tokens $tokens): void
    {
        $useParentheses = $this->configuration['use_parentheses'];

        for ($index = $tokens->count() - 1; $index >= 0; --$index) {
            if (!$tokens[$index]->isGivenKind(\T_INSTANCEOF)) {
                continue;
            }

            if (!$this->isNegated($tokens, $index)) {
                continue;
            }

            [$start, $end] = $this->getExpressionBounds($tokens, $index);
            $hasParentheses = $this->hasParentheses($tokens, $start, $end);

            if ($useParentheses === $hasParentheses) {
                continue;
            }

            if ($useParentheses) {
                $this->addParentheses($tokens, $start, $end);
            } else {
                $this->removeParentheses($tokens, $start, $end);
            }
        }
    }

    private function isNegated(Tokens $tokens, int $instanceofIndex): bool
    {
        $index = $tokens->getPrevMeaningfulToken($instanceofIndex);

        while (($index = $tokens->getPrevMeaningfulToken($index)) !== null) {
            if ($tokens[$index]->equals('(')) {
                continue;
            }

            return $tokens[$index]->equals('!');
        }

        return false;
    }

    /**
     * @return array{0: int, 1: int}
     */
    private function getExpressionBounds(Tokens $tokens, int $instanceofIndex): array
    {
        $start = $tokens->getPrevMeaningfulToken($instanceofIndex);
        $class = $tokens->getNextMeaningfulToken($instanceofIndex);

        $end = $class;
        while (($next = $tokens->getNextMeaningfulToken($end)) !== null) {
            if ($tokens[$next]->isGivenKind([\T_STRING, \T_NS_SEPARATOR])) {
                $end = $next;

                continue;
            }

            break;
        }

        return [$start, $end];
    }

    private function hasParentheses(Tokens $tokens, int $startIndex, int $endIndex): bool
    {
        $openIndex = $tokens->getPrevMeaningfulToken($startIndex);
        $closeIndex = $tokens->getNextMeaningfulToken($endIndex);

        return
            $tokens[$openIndex]->equals('(')
            && $tokens[$closeIndex]->equals(')');
    }

    private function addParentheses(Tokens $tokens, int $startIndex, int $endIndex): void
    {
        $tokens->insertSlices([
            $startIndex => new Token('('),
            $endIndex + 1 => new Token(')'), // +1 to insert after $endIndex
        ]);
    }

    private function removeParentheses(Tokens $tokens, int $startIndex, int $endIndex): void
    {
        $openIndex = $tokens->getPrevMeaningfulToken($startIndex);
        $closeIndex = $tokens->getNextMeaningfulToken($endIndex);

        $tokens->clearTokenAndMergeSurroundingWhitespace($closeIndex);
        $tokens->clearTokenAndMergeSurroundingWhitespace($openIndex);
    }
}
