name: Composer's JSON and lock cleanup

on:
  push:
    branches:
      - "dependabot/**"
    paths:
      - "dev-tools/composer.lock"

permissions:
  pull-requests: write
  contents: write

jobs:
  automate:
    name: Automate
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update
        run: |
          git config user.name "dependabot[bot]"
          git config user.email "49699333+dependabot[bot]@users.noreply.github.com"
          composer --working-dir=dev-tools update --bump-after-update --lock
          git add dev-tools/composer.*
          git commit -m "update json and lock files" || echo "nothing to commit"
          git push
