# Flow for self-approving the PRs, used by maintainers for cases aligned between them.
# To trigger it, maintainer need to commit and push:
# $ git commit -m "self-approval" --allow-empty

name: self-approval

on:
  - pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  job:
    runs-on: ubuntu-latest
    if: ${{ contains(fromJson('["julienfalque", "keradus", "keradus-ci", "kubawerlos", "localheinz", "Wirone"]'), github.actor) }}
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      MARKER: "self-approval"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.after }}
      - name: get marker
        id: marker
        run: |
          msg=$(git show -s --format=%s ${{ github.event.after }})
          echo $msg
          indicator=$([[ $msg == $MARKER ]] && echo yes || echo no)
          echo $indicator
          echo "indicator_value=${indicator}" >> "$GITHUB_OUTPUT"
      - name: skip
        if: steps.marker.outputs.indicator_value != 'yes'
        run: echo no marker detected, skipping
      - name: self-approve
        if: steps.marker.outputs.indicator_value == 'yes'
        run: |
          echo self-approving
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
